"""initial schema

Revision ID: 9badf696a03d
Revises: 
Create Date: 2026-09-29 15:51:09.552466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9badf696a03d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('professor', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('eclass_username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("eclass_username = lower(btrim(eclass_username)) AND eclass_username <> ''", name=op.f('ck_users_username_normalized')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('eclass_username', name=op.f('uq_users_eclass_username'))
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_activities_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_course_id'), 'activities', ['course_id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('count >= 0', name=op.f('ck_ai_usage_count_not_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', name=op.f('pk_ai_usage'))
    )
    op.create_table('eclass_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('autosync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'invalid')", name=op.f('ck_eclass_credentials_status')),
    sa.CheckConstraint('(encrypted_password IS NULL) = (key_version IS NULL)', name=op.f('ck_eclass_credentials_key_version_with_password')),
    sa.CheckConstraint('NOT autosync_enabled OR encrypted_password IS NOT NULL', name=op.f('ck_eclass_credentials_autosync_needs_password')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_eclass_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_eclass_credentials'))
    )
    op.create_table('eclass_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_cookie', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_eclass_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_eclass_sessions'))
    )
    op.create_index(op.f('ix_eclass_sessions_expires_at'), 'eclass_sessions', ['expires_at'], unique=False)
    op.create_table('enrollments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name=op.f('pk_enrollments'))
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_table('sections',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_sections_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'number', name=op.f('pk_sections'))
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='running', nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('new_items', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'done', 'error')", name=op.f('ck_sync_runs_status')),
    sa.CheckConstraint("trigger IN ('login', 'button', 'schedule')", name=op.f('ck_sync_runs_trigger')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_user_id'), 'sync_runs', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('eclass_url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('mimetype', sa.String(length=120), nullable=True),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('n_chars', sa.Integer(), nullable=True),
    sa.Column('extract_error', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_materials_activity_id_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('activity_id', 'filename', name='uq_materials_activity_filename')
    )
    op.create_index(op.f('ix_materials_activity_id'), 'materials', ['activity_id'], unique=False)
    op.create_table('user_assignments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_text', sa.String(length=40), nullable=True),
    sa.Column('submission_status', sa.Text(), nullable=True),
    sa.Column('grading_status', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_user_assignments_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'activity_id', name=op.f('pk_user_assignments'))
    )
    op.create_table('material_pages',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_pages_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'page', name=op.f('pk_material_pages'))
    )
    op.create_index('ix_material_pages_tsv', 'material_pages', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('pack_notes',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_pack_notes_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'sha256', 'chunk', name=op.f('pk_pack_notes'))
    )
    op.create_table('progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('studied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_progress_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'material_id', name=op.f('pk_progress'))
    )
    op.create_table('study_packs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flashcards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quiz', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_study_packs_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_packs')),
    sa.UniqueConstraint('material_id', 'language', name='uq_study_packs_material_language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_packs')
    op.drop_table('progress')
    op.drop_table('pack_notes')
    op.drop_index('ix_material_pages_tsv', table_name='material_pages', postgresql_using='gin')
    op.drop_table('material_pages')
    op.drop_table('user_assignments')
    op.drop_index(op.f('ix_materials_activity_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_sync_runs_user_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('sections')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_eclass_sessions_expires_at'), table_name='eclass_sessions')
    op.drop_table('eclass_sessions')
    op.drop_table('eclass_credentials')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_activities_course_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
