"""Study packs (summary, key concepts, flashcards, quiz) for the hosted site, generated by the scheduled job.

Same prompts and chunking as the Mac version (eclass/study.py). A pack belongs to a material version and is shared
by every student of the course. Generation stays within the shared Gemini quota: a few packs per scheduled run
(PACKS_PER_RUN), and a run stops at the provider's daily limit; notes of long files are stored per chunk
(pack_notes), so the next run resumes where this one stopped.
"""
import logging
import time

from sqlalchemy import exists, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session, sessionmaker

from eclass import config as eclass_config
from eclass.ai import AIError, DailyLimitReached, get_provider
from eclass.study import (CHUNK_CHARS, MAX_AI_CHARS, MIN_AI_CHARS, NOTES_SCHEMA, NOTES_SYSTEM, STUDY_SCHEMA,
                          chunk_pages, clean_result, language, study_system)
from web import config
from web.models import Activity, Course, Material, MaterialPage, PackNote, StudyPack

log = logging.getLogger("web.packs")


def provider():
    """The configured AI chain without local-only providers (Ollama) when hosted."""
    chain = get_provider(timeout=eclass_config.AI_TIMEOUT)
    if config.hosted():
        chain.providers = [p for p in chain.providers if p.name != "ollama"]
        if not chain.providers:
            raise AIError("no hosted AI provider configured")
    return chain


def pending(db: Session, code: str, limit: int) -> list[Material]:
    """Materials with readable text and no pack in this language for their current version, newest first."""
    current = exists().where(StudyPack.material_id == Material.id, StudyPack.language == code,
                             StudyPack.sha256 == Material.sha256)
    return db.scalars(select(Material).where(Material.sha256.is_not(None), Material.extract_error.is_(None),
                                             Material.n_chars.between(MIN_AI_CHARS, MAX_AI_CHARS), ~current)
                      .order_by(Material.first_seen_at.desc(), Material.id.desc()).limit(limit)).all()


def _notes(db: Session, ai, material: Material, course: str, chunks: list[str]) -> str:
    """Map step for long files, resumable: every chunk's notes are committed as soon as they exist."""
    done = {n.chunk: n.notes for n in db.scalars(select(PackNote).where(
        PackNote.material_id == material.id, PackNote.sha256 == material.sha256))}
    for i, chunk in enumerate(chunks):
        if i not in done:
            done[i] = ai.complete_json(NOTES_SYSTEM, f"Course: {course}\nFile: {material.filename}\n\n{chunk}",
                                       NOTES_SCHEMA, max_tokens=1500)["notes"]
            db.add(PackNote(material_id=material.id, sha256=material.sha256, chunk=i, notes=done[i]))
            db.commit()
    return "\n\n".join(f"[Part {i + 1}]\n{done[i]}" for i in range(len(chunks)))


def build(db: Session, ai, material: Material) -> dict:
    """Generate and store the pack of one material in the configured study language."""
    activity = db.get(Activity, material.activity_id)
    course = db.get(Course, activity.course_id).name
    pages = [(p.page, p.text) for p in db.scalars(select(MaterialPage).where(
        MaterialPage.material_id == material.id).order_by(MaterialPage.page))]
    chunks = chunk_pages(pages)
    if not chunks:
        raise ValueError("no text to study")
    text = chunks[0] if len(chunks) == 1 else _notes(db, ai, material, course, chunks)
    while len(text) > CHUNK_CHARS:  # extremely long notes: condense once more
        text = "\n\n".join(ai.complete_json(NOTES_SYSTEM, part, NOTES_SCHEMA, max_tokens=1500)["notes"]
                           for part in chunk_pages([(0, text)]))
    code, lang_name = language()
    user = f"Course: {course}\nMaterial: {activity.name} ({material.filename})\n\n{text}"
    result = clean_result(ai.complete_json(study_system(lang_name), user, STUDY_SCHEMA, max_tokens=4000))
    values = {"sha256": material.sha256, "provider": ai.name, "model": ai.model, "summary": result["summary"],
              "concepts": result["key_concepts"], "flashcards": result["flashcards"], "quiz": result["quiz"]}
    db.execute(insert(StudyPack).values(material_id=material.id, language=code, **values)
               .on_conflict_do_update(constraint="uq_study_packs_material_language", set_=values))
    db.commit()
    return result


def generate_pending(sessions: sessionmaker, ai, limit: int, pause: float = 2.0, sleep=time.sleep) -> dict:
    stats = {"generated": 0, "failed": 0, "stopped": None}
    code, _ = language()
    with sessions() as db:
        for material in pending(db, code, limit):
            try:
                build(db, ai, material)
                stats["generated"] += 1
            except DailyLimitReached:
                db.rollback()
                stats["stopped"] = "daily limit"
                break
            except Exception as exc:  # one bad file must not stop the queue
                db.rollback()
                stats["failed"] += 1
                log.warning("study pack for material %s failed: %s", material.id, type(exc).__name__)
            sleep(pause)
    return stats


def pack_for(db: Session, material_id: int) -> StudyPack | None:
    """The current pack of a material (the configured study language first)."""
    code, _ = language()
    return db.scalar(select(StudyPack).join(Material, Material.id == StudyPack.material_id)
                     .where(StudyPack.material_id == material_id, StudyPack.sha256 == Material.sha256)
                     .order_by((StudyPack.language == code).desc()).limit(1))


def with_packs(db: Session, material_ids) -> set[int]:
    """Which of these materials have a current pack."""
    ids = list(material_ids)
    if not ids:
        return set()
    return set(db.scalars(select(StudyPack.material_id).join(Material, Material.id == StudyPack.material_id)
                          .where(StudyPack.material_id.in_(ids), StudyPack.sha256 == Material.sha256)))
